# Generated by Django 4.2.9 on 2024-01-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='pin',
            new_name='pins',
        ),
    ]
